[package]
authors = ["The ClamAV Team <clamav-bugs@external.cisco.com>"]
edition = "2021"
name = "clamav_rust"
version = "0.0.1"

[dependencies]
flate2 = "1"
hex = "0.4"
libc = "0.2"
log = { version = "0.4", features = ["std"] }
sha2 = "0.10"
tempfile = "3"
thiserror = "1"
image = "0.25"
rustdct = "0.7"
transpose = "0.2"
num-traits = "0.2"
base64 = "0.21"
sha1 = "0.10"
unicode-segmentation = "1.10"
bindgen = "0.65"
onenote_parser = { git = "https://github.com/Cisco-Talos/onenote.rs.git", branch = "CLAM-2329-new-from-slice" }
hex-literal = "0.4"
inflate = "0.4"
bzip2-rs = "0.1"
byteorder = "1.5"
delharc = "0.6"
clam-sigutil = { git = "https://github.com/Cisco-Talos/clamav-signature-util", tag = "1.2.4" }
tar = "0.4.43"
md5 = "0.7.0"
openssl = "0.10.70"
glob = "0.3.1"
indexmap = "2.10.0"

[features]
not_ready = []

[lib]
crate-type = ["staticlib"]
name = "clamav_rust"

[build-dependencies]
cbindgen = { version ="0.25", default-features = false }
bindgen = "0.65"
