[package]
authors = ["The ClamAV Team <clamav-bugs@external.cisco.com>"]
edition = "2018"
name = "clamav_rust"
version = "0.0.1"

[dependencies]
flate2 = "1"
hex = "0.4"
libc = "0.2"
log = { version = "0.4", features = ["std"] }
sha2 = "0.10"
tempfile = "3"
thiserror = "1"
image = "0.24"
rustdct = "0.7"
transpose = "0.2"
num-traits = "0.2"
base64 = "0.21.0"
sha1 = "0.10.5"
unicode-segmentation = "1.10.1"
bindgen = "0.65"
onenote_parser = { git = "https://github.com/Cisco-Talos/onenote.rs.git", branch = "CLAM-2329-new-from-slice" }
hex-literal = "0.4.1"

[lib]
crate-type = ["staticlib"]
name = "clamav_rust"

[build-dependencies]
cbindgen = { version ="0.25", default-features = false }
bindgen = "0.65"
